package com.snxun.mp.greendaolib.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.snxun.mp.greendaolib.table.EmailMessageTable;

import com.snxun.mp.greendaolib.dao.EmailMessageTableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig emailMessageTableDaoConfig;

    private final EmailMessageTableDao emailMessageTableDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        emailMessageTableDaoConfig = daoConfigMap.get(EmailMessageTableDao.class).clone();
        emailMessageTableDaoConfig.initIdentityScope(type);

        emailMessageTableDao = new EmailMessageTableDao(emailMessageTableDaoConfig, this);

        registerDao(EmailMessageTable.class, emailMessageTableDao);
    }
    
    public void clear() {
        emailMessageTableDaoConfig.clearIdentityScope();
    }

    public EmailMessageTableDao getEmailMessageTableDao() {
        return emailMessageTableDao;
    }

}
